defaults: &defaults
  docker:
    - image: circleci/node:8.10.0
version: 1
jobs:
  buildAndPush:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: docker build
          command: docker build -t taijuten/circle-node-awscli:${CIRCLE_BUILD_NUM} -t taijuten/circle-node-awscli:latest .
      - run:
          name: docker push
          command: docker push
workflows:
  version: 2
  build_and_push:
    jobs:
      - buildAndPush
