defaults: &defaults
  docker:
    - image: circleci/node:8.10.0
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: docker login
          command: docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
      - run:
          name: docker build
          command: docker build -t taijuten/circle-node-awscli:${CIRCLE_BUILD_NUM} -t taijuten/circle-node-awscli:latest .
      - run:
          name: docker push
          command: docker push taijuten/circle-node-awscli
workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          context: docker
